/**
 * @author Bruno Pelatieri Goulart
 * @version 1.0.0
 * @date 2025-11-01
 * @license MIT
 * @package SQL_DDL
 * 
 * Script SQL para criação de tabelas no Supabase
 *
 */

-- ==========================================
-- TABELAS PARA SISTEMA DE LEADS
-- Execute este script no SQL Editor do Supabase
-- ==========================================

-- Tabela para leads não qualificados (campos individuais)
CREATE TABLE IF NOT EXISTS lead_unqualified (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    controle_u VARCHAR(255) NOT NULL UNIQUE,
    nome VARCHAR(255),
    whatsapp VARCHAR(20),
    email VARCHAR(255),
    site VARCHAR(500),
    faturamento VARCHAR(100),
    ip VARCHAR(45),
    user_agent TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Tabela para leads qualificados (formulário completo)
CREATE TABLE IF NOT EXISTS lead_qualified (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    controle_u VARCHAR(255) NOT NULL,
    nome VARCHAR(255) NOT NULL,
    whatsapp VARCHAR(20) NOT NULL,
    email VARCHAR(255) NOT NULL,
    site VARCHAR(500),
    faturamento VARCHAR(100) NOT NULL,
    ip VARCHAR(45),
    user_agent TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Índices para otimização de consultas
CREATE INDEX IF NOT EXISTS idx_lead_unqualified_controle_u ON lead_unqualified(controle_u);
CREATE INDEX IF NOT EXISTS idx_lead_unqualified_email ON lead_unqualified(email);
CREATE INDEX IF NOT EXISTS idx_lead_unqualified_created_at ON lead_unqualified(created_at DESC);

CREATE INDEX IF NOT EXISTS idx_lead_qualified_controle_u ON lead_qualified(controle_u);
CREATE INDEX IF NOT EXISTS idx_lead_qualified_email ON lead_qualified(email);
CREATE INDEX IF NOT EXISTS idx_lead_qualified_created_at ON lead_qualified(created_at DESC);

-- Função para atualizar updated_at automaticamente
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger para lead_unqualified
DROP TRIGGER IF EXISTS update_lead_unqualified_updated_at ON lead_unqualified;
CREATE TRIGGER update_lead_unqualified_updated_at
    BEFORE UPDATE ON lead_unqualified
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- Trigger para lead_qualified
DROP TRIGGER IF EXISTS update_lead_qualified_updated_at ON lead_qualified;
CREATE TRIGGER update_lead_qualified_updated_at
    BEFORE UPDATE ON lead_qualified
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- ==========================================
-- ROW LEVEL SECURITY (RLS)
-- Descomente e configure conforme suas necessidades
-- ==========================================

-- Habilita RLS nas tabelas
-- ALTER TABLE lead_unqualified ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE lead_qualified ENABLE ROW LEVEL SECURITY;

-- Política para permitir inserções de usuários anônimos (API key)
-- CREATE POLICY "Permitir inserção via API" ON lead_unqualified
--     FOR INSERT
--     TO anon
--     WITH CHECK (true);

-- CREATE POLICY "Permitir inserção via API" ON lead_qualified
--     FOR INSERT
--     TO anon
--     WITH CHECK (true);

-- Política para permitir atualizações via API
-- CREATE POLICY "Permitir atualização via API" ON lead_unqualified
--     FOR UPDATE
--     TO anon
--     USING (true)
--     WITH CHECK (true);

-- Política para leitura apenas autenticada
-- CREATE POLICY "Permitir leitura autenticada" ON lead_unqualified
--     FOR SELECT
--     TO authenticated
--     USING (true);

-- CREATE POLICY "Permitir leitura autenticada" ON lead_qualified
--     FOR SELECT
--     TO authenticated
--     USING (true);

-- ==========================================
-- VIEWS ÚTEIS
-- ==========================================

-- View para análise de conversão
CREATE OR REPLACE VIEW vw_conversao_leads AS
SELECT 
    DATE(lq.created_at) as data,
    COUNT(DISTINCT lu.controle_u) as leads_unqualified,
    COUNT(DISTINCT lq.controle_u) as leads_qualified,
    ROUND(
        (COUNT(DISTINCT lq.controle_u)::DECIMAL / 
         NULLIF(COUNT(DISTINCT lu.controle_u), 0) * 100), 
        2
    ) as taxa_conversao
FROM lead_unqualified lu
LEFT JOIN lead_qualified lq ON lu.controle_u = lq.controle_u
GROUP BY DATE(lq.created_at)
ORDER BY data DESC;

-- View para últimos leads qualificados
CREATE OR REPLACE VIEW vw_ultimos_leads_qualified AS
SELECT 
    id,
    controle_u,
    nome,
    whatsapp,
    email,
    site,
    faturamento,
    created_at
FROM lead_qualified
ORDER BY created_at DESC
LIMIT 100;

-- ==========================================
-- COMENTÁRIOS NAS TABELAS
-- ==========================================

COMMENT ON TABLE lead_unqualified IS 'Leads não qualificados - captura campos individuais durante preenchimento';
COMMENT ON TABLE lead_qualified IS 'Leads qualificados - formulário completo enviado';

COMMENT ON COLUMN lead_unqualified.controle_u IS 'Identificador único do lead (parâmetro u da URL)';
COMMENT ON COLUMN lead_unqualified.nome IS 'Nome completo do lead';
COMMENT ON COLUMN lead_unqualified.whatsapp IS 'WhatsApp no formato (99) 99999-9999';
COMMENT ON COLUMN lead_unqualified.email IS 'E-mail do lead';
COMMENT ON COLUMN lead_unqualified.site IS 'Website da empresa (opcional)';
COMMENT ON COLUMN lead_unqualified.faturamento IS 'Faixa de faturamento anual';
COMMENT ON COLUMN lead_unqualified.ip IS 'Endereço IP do lead';
COMMENT ON COLUMN lead_unqualified.user_agent IS 'User Agent do navegador';

-- ==========================================
-- CONSULTAS ÚTEIS PARA ANÁLISE
-- ==========================================

-- Total de leads por status
-- SELECT 
--     'Unqualified' as status,
--     COUNT(*) as total
-- FROM lead_unqualified
-- UNION ALL
-- SELECT 
--     'Qualified' as status,
--     COUNT(*) as total
-- FROM lead_qualified;

-- Leads por faixa de faturamento
-- SELECT 
--     faturamento,
--     COUNT(*) as total
-- FROM lead_qualified
-- WHERE faturamento IS NOT NULL
-- GROUP BY faturamento
-- ORDER BY total DESC;

-- Taxa de conversão geral
-- SELECT 
--     COUNT(DISTINCT lu.controle_u) as total_unqualified,
--     COUNT(DISTINCT lq.controle_u) as total_qualified,
--     ROUND(
--         (COUNT(DISTINCT lq.controle_u)::DECIMAL / 
--          NULLIF(COUNT(DISTINCT lu.controle_u), 0) * 100), 
--         2
--     ) as taxa_conversao_pct
-- FROM lead_unqualified lu
-- LEFT JOIN lead_qualified lq ON lu.controle_u = lq.controle_u;